Class msg.createVerifyReservationDmde Extends (Ens.Request, %JSON.Adaptor)
{

Property plaque As %String;

Storage Default
{
<Data name="createVerifyReservationDmdeDefaultData">
<Subscript>"createVerifyReservationDmde"</Subscript>
<Value name="1">
<Value>categorie</Value>
</Value>
<Value name="2">
<Value>plaque</Value>
</Value>
</Data>
<DefaultData>createVerifyReservationDmdeDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
